spring:
  profiles:
    active:
      - h2
  sql:
    init:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none

taco:
  orders:
    page-size: 5
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/tacocloud
    username: tacodb
    password: tacopassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: mariadb
debug: false

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:./testdb;AUTO_SERVER=true
  sql:
    init:
      platform: h2

---
spring:
  config:
    activate:
      on-profile: initdb
  sql:
    init:
      enabled: true
